{
 "title": "Docker and OS Metrics for Raspberry Pi",
 "description": "Dashboard with details of the container and host OS metrics for Raspberry Pi by Oijkn.",
 "tags": [
  "cAdvisor",
  "node-exporter",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Host", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "diskmountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{fstype!~\"tmpfs\",mountpoint!~\"/etc/.*\"},mountpoint)"
    }
   },
   {
    "name": "diskdevice",
    "label": "Diskdevice",
    "query": {
     "query": "label_values(node_disk_read_bytes_total,device)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_tasks_state{},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time during which Pi is in operation",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total containers running",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\",image=~\"(.)+\"})"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}[$interval])) * 100) "
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "description": "Total containers running",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100 "
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "description": "Total used disk space",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"})/ node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "Hardware temperature",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{job=\"$job\"}[$interval]) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1 Minute" },
    { "expr": "node_load5", "legendFormat": "5 Minutes" },
    { "expr": "node_load15", "legendFormat": "15 Minutes" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Availabble" }
   ]
  },
  {
   "title": "Used Disk Space ${diskmountpoint}",
   "type": "timeseries",
   "description": "Disk space used",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (device) (node_filesystem_size_bytes{fstype!~\"tmpfs\"}-node_filesystem_avail_bytes{fstype!~\"tmpfs\"})",
     "legendFormat": "used {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO ${diskdevice}",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{}[1m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "- irate(node_disk_written_bytes_total{}[1m])",
     "legendFormat": "{{device}} - Writes"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{}[1m])",
     "legendFormat": "{{device}} - io time"
    }
   ]
  },
  {
   "title": "Disk ${diskmountpoint}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "diskmountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Used Disk Space",
     "type": "timeseries",
     "description": "Disk space used",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs\",mountpoint=\"${diskmountpoint}\"}",
       "legendFormat": "max {{device}}"
      },
      {
       "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs\",mountpoint=\"${diskmountpoint}\"}-node_filesystem_avail_bytes{fstype!~\"tmpfs\",mountpoint=\"${diskmountpoint}\"})",
       "legendFormat": "used {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Diskdevice ${diskdevice}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "diskdevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=\"${diskdevice}\"}[1m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "- irate(node_disk_written_bytes_total{device=\"${diskdevice}\"}[1m])",
       "legendFormat": "{{device}} - Writes completed"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{device=\"${diskdevice}\"}[1m])",
       "legendFormat": "{{device}} - io time"
      }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Network Traffic (All Containers)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "sent {{device}} "
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 54 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\"}-container_memory_usage_bytes{name!=\"\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\"}) by (name)"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container ${container}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"${container}\"}[$__range])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{name=\"${container}\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "- rate(container_network_receive_bytes_total{instance=~\"$node\",name=~\"${container}\"}[$interval])   ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",name=~\"${container}\"}[$interval]))",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "I/O Rx FS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id,csv) (irate(container_fs_writes_bytes_total{image!=\"\",device!~\"/dev/dm.*\",name=\"${container}\"}[$interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "I/O Tx FS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id,csv) (irate(container_fs_reads_bytes_total{image!=\"\",device!~\"/dev/dm.*\",name=\"${container}\"}[$interval])) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}